import { SubnetGroup } from "../subnet-group.ts";
import { IPV4_ADDRESS_RANGE } from "./ipv4-address-range.ts";
import { IPV6_ADDRESS_RANGE } from "./ipv6-address-range.ts";

// Define the categories first
const LOCALHOST = new SubnetGroup(IPV4_ADDRESS_RANGE.LOOPBACK, IPV6_ADDRESS_RANGE.LOOPBACK);

const PRIVATE = new SubnetGroup(
  IPV4_ADDRESS_RANGE.PRIVATE_IP,
  IPV6_ADDRESS_RANGE.LINK_SCOPED_UNICAST,
  IPV6_ADDRESS_RANGE.UNIQUE_LOCAL,
);

const RESERVED = new SubnetGroup(
  IPV4_ADDRESS_RANGE.BROADCAST_THIS,
  IPV4_ADDRESS_RANGE.CARRIER_GRADE_NAT,
  IPV4_ADDRESS_RANGE.LINK_LOCAL,
  IPV4_ADDRESS_RANGE.IETF_PROTOCOL_ASSIGNMENTS,
  IPV4_ADDRESS_RANGE.DS_LITE,
  IPV4_ADDRESS_RANGE.TEST_NET_1,
  IPV4_ADDRESS_RANGE["6TO4_RELAY_ANYCAST"],
  IPV4_ADDRESS_RANGE.BENCHMARKING,
  IPV4_ADDRESS_RANGE.TEST_NET_2,
  IPV4_ADDRESS_RANGE.TEST_NET_3,
  IPV4_ADDRESS_RANGE.MULTICAST,
  IPV4_ADDRESS_RANGE.RESERVED_1,
  IPV4_ADDRESS_RANGE.LIMITED_BROADCAST,
  IPV6_ADDRESS_RANGE.UNSPECIFIED,
  IPV6_ADDRESS_RANGE.IPV4_IPV6_TRANSLATION,
  IPV6_ADDRESS_RANGE.DISCARD_ONLY,
  IPV6_ADDRESS_RANGE.TEREDO,
  IPV6_ADDRESS_RANGE.DOCUMENTATION,
  IPV6_ADDRESS_RANGE["6TO4"],
  IPV6_ADDRESS_RANGE.MULTICAST,
  IPV6_ADDRESS_RANGE.ORCHIDV2,
);

// Define the SPECIAL category using the above variables
const SPECIAL = new SubnetGroup(LOCALHOST, PRIVATE, RESERVED);

// Create the final object with all categories
export const IP_CATEGORY = {
  LOCALHOST,
  PRIVATE,
  RESERVED,
  SPECIAL,
} as const;
