import { IPV4_ADDRESS_RANGE } from "./ipv4/ipv4-address-ranges.js";
import { IPV6_ADDRESS_RANGE } from "./ipv6/ipv6-address-ranges.js";
export const IP_CATEGORY = {
  LOCALHOST: {
    IPV4: [...IPV4_ADDRESS_RANGE.LOOPBACK],
    IPV6: [...IPV6_ADDRESS_RANGE.LOOPBACK],
  },

  PRIVATE: {
    IPV4: [...IPV4_ADDRESS_RANGE.PRIVATE_IP],
    IPV6: [...IPV6_ADDRESS_RANGE.LINK_SCOPED_UNICAST, ...IPV6_ADDRESS_RANGE.UNIQUE_LOCAL],
  },

  RESERVED: {
    IPV4: [
      ...IPV4_ADDRESS_RANGE.BROADCAST_THIS,
      ...IPV4_ADDRESS_RANGE.CARRIER_GRADE_NAT,
      ...IPV4_ADDRESS_RANGE.LINK_LOCAL,
      ...IPV4_ADDRESS_RANGE.IETF_PROTOCOL_ASSIGNMENTS,
      ...IPV4_ADDRESS_RANGE.DS_LITE,
      ...IPV4_ADDRESS_RANGE.TEST_NET_1,
      ...IPV4_ADDRESS_RANGE["6TO4_RELAY_ANYCAST"],
      ...IPV4_ADDRESS_RANGE.BENCHMARKING,
      ...IPV4_ADDRESS_RANGE.TEST_NET_2,
      ...IPV4_ADDRESS_RANGE.TEST_NET_3,
      ...IPV4_ADDRESS_RANGE.MULTICAST,
      ...IPV4_ADDRESS_RANGE.RESERVED_1,
      ...IPV4_ADDRESS_RANGE.LIMITED_BROADCAST,
    ],
    IPV6: [
      ...IPV6_ADDRESS_RANGE.UNSPECIFIED,
      ...IPV6_ADDRESS_RANGE.IPV4_IPV6_TRANSLATION,
      ...IPV6_ADDRESS_RANGE.DISCARD_ONLY,
      ...IPV6_ADDRESS_RANGE.TEREDO,
      ...IPV6_ADDRESS_RANGE.DOCUMENTATION,
      ...IPV6_ADDRESS_RANGE["6TO4"],
      ...IPV6_ADDRESS_RANGE.MULTICAST,
      ...IPV6_ADDRESS_RANGE.ORCHIDV2,
    ],
  },
} as const;
